### ISSUE TITLE
测试结果有关的问题

### ISSUE THREAD

**Issue by atomishcv** [BIT-DA/I2V-GAN#10]
![000001_fake_A](https://user-images.githubusercontent.com/88809942/171080339-d00356e7-22c5-43c9-b41c-9e02b6d203e9.png)
![000001_fake_B](https://user-images.githubusercontent.com/88809942/171080343-7cde40d3-0757-4b88-862b-ae43bd7e0132.png)
![000001_real_A](https://user-images.githubusercontent.com/88809942/171080344-43280afe-bb7d-470b-af61-21af3dc8c31b.png)
![000001_real_B](https://user-images.githubusercontent.com/88809942/171080346-3a30ae11-0b34-476e-9431-682cdf656e31.png)
![000001_rec_A](https://user-images.githubusercontent.com/88809942/171080347-1b4070b4-7871-4cc5-82c2-27cc44ff1c1a.png)
![000001_rec_B](https://user-images.githubusercontent.com/88809942/171080350-4e644847-37ac-4281-bbf4-7d866618fafb.png)
抱歉，再次叨扰您。昨天我跑了测试的代码，我想问结果中的_fake_A, _fake_B, _rec_A, _rec_B分别代表什么意思呢？为什么没有红外影像变为可见光的结果呢？

**Comment by ThornyGuyu** [comment]
我想了解下大哥您怎么跑起来的。。。

**Comment by atomishcv** [comment]
@ThornyGuyu 按照他给的train部分来设置参数就可以跑了

**Comment by paperheart** [comment]
你好，A代表红外风格，B可见光风格，其中fake的概念就是代表是生成出来的结果，rec的概念是代表重构的结果。逻辑顺序为real_A送入生成器G_B生成fake_B，即生成器将送入的真实红外变成了可见光风格；而再将fake_B送入生成器G_A重新得到重构A领域风格结果，记作rec_A，即为生成的可见光风格重构回了原本的红外风格的结果。real_B→fake_A→rec_B同理。

**Comment by paperheart** [comment]
> ![000001_fake_A](https://user-images.githubusercontent.com/88809942/171080339-d00356e7-22c5-43c9-b41c-9e02b6d203e9.png) ![000001_fake_B](https://user-images.githubusercontent.com/88809942/171080343-7cde40d3-0757-4b88-862b-ae43bd7e0132.png) ![000001_real_A](https://user-images.githubusercontent.com/88809942/171080344-43280afe-bb7d-470b-af61-21af3dc8c31b.png) ![000001_real_B](https://user-images.githubusercontent.com/88809942/171080346-3a30ae11-0b34-476e-9431-682cdf656e31.png) ![000001_rec_A](https://user-images.githubusercontent.com/88809942/171080347-1b4070b4-7871-4cc5-82c2-27cc44ff1c1a.png) ![000001_rec_B](https://user-images.githubusercontent.com/88809942/171080350-4e644847-37ac-4281-bbf4-7d866618fafb.png) 抱歉，再次叨扰您。昨天我跑了测试的代码，我想问结果中的_fake_A, _fake_B, _rec_A, _rec_B分别代表什么意思呢？为什么没有红外影像变为可见光的结果呢？

你好，A代表红外风格，B可见光风格，其中fake的概念就是代表是生成出来的结果，rec的概念是代表重构的结果。逻辑顺序为real_A送入生成器G_B生成fake_B，即生成器将送入的真实红外变成了可见光风格；而再将fake_B送入生成器G_A重新得到重构A领域风格结果，记作rec_A，即为生成的可见光风格重构回了原本的红外风格的结果。real_B→fake_A→rec_B同理。

**Comment by atomishcv** [comment]
@paperheart 非常感谢！
