### ISSUE TITLE
学术求助，您好，我是一名图像算法工程师，对您的研究很感兴趣，运行代码的过程中出现了一些问题，可以为我解答一下吗？

### ISSUE THREAD

**Issue by gwq2018** [BIT-DA/I2V-GAN#2]
您好 请教您一个问题，在贵公司 红外真彩转换I2V-GAN 算法中出现了一个问题能为我解答一下吗？运行这个代码需要多大的显存才够呢？

![image](https://user-images.githubusercontent.com/37999134/143514592-7a46f285-a924-48b8-916d-db2027077c8e.png)

**Comment by paperheart** [comment]
你好，提示fake_B0不存在是因为之前显存不够没有成功计算出结果，运行需要的显存为13G。

**Comment by gwq2018** [comment]
> 你好，提示fake_B0不存在是因为之前显存不够没有成功计算出结果，运行需要的显存为13G。

好的，谢谢

**Comment by gwq2018** [comment]
好的，非常谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BIT-DA/I2V-GAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BIT-DA/I2V-GAN] 学术求助，您好，我是一名图像算法工程师，对您的研究很感兴趣，运行代码的过程中出现了一些问题，可以为我解答一下吗？ (Issue #2)





 
你好，提示fake_B0不存在是因为之前显存不够没有成功计算出结果，运行需要的显存为13G。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
