### ISSUE TITLE
请问我在复现代码时候出现这个路径找不到问题怎么解决？

### ISSUE THREAD

**Issue by changyangmimeng** [BIT-DA/I2V-GAN#5]
assert os.path.isdir(dir), '%s is not a valid directory' % dir
AssertionError: ../D:/I2V-GAN-main/IRVI/single/traffic/trainA is not a valid directory

**Comment by BingfengHan** [comment]
路径没有写对，请尝试使用绝对路径

**Comment by changyangmimeng** [comment]
您的邮件已收到！谢谢！

**Comment by changyangmimeng** [comment]
非常感谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月31日(周四) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BIT-DA/I2V-GAN] 请问我在复现代码时候出现这个路径找不到问题怎么解决？ (Issue #5)




 
路径没有写对，请尝试使用绝对路径
