### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by ycm910** [BIT-DA/I2V-GAN#6]
请问这个代码在运行时一直卡顿在这一步没有反应了是什么原因呢？
我是在windows，cpu环境下运行的。

**Comment by ycm910** [comment]
create web directory ./checkpoints\experiment_name\web... 卡在了这里

**Comment by BingfengHan** [comment]
看起来是路径问题/

**Comment by ycm910** [comment]
> 看起来是路径问题/

感谢您的回复，不是路径的问题，应该是训练环境的问题，需要等很久的时间才会有运行结果出现。
