### ISSUE TITLE
测试结果有问题

### ISSUE THREAD

**Issue by songyn95** [BIT-DA/I2V-GAN#7]
你好，我使用了预训练模型，直接进行测试我的数据，testA文件夹：测试集    testB文件夹：对应的ground truth，结果发现：
1. 生成结果中 real_A.png和real_B.png分别和 testA testB文件夹内的数据一样
2. 测试集为红外测试集，生成的结果 real_A.png仍然是红外，只是大小不同

问题如下：
1. 结果是否是生成的real_A.png？ 如果是，结果和输入没啥变化，换了提供的测试集也是这样的效果，原因是什么？

**Comment by BingfengHan** [comment]
请用你的数据训练

**Comment by songyn95** [comment]
> 

你好，必须要用自己的数据集先训练，在用生成的模型进行测试是吗？ 
另外，我使用你们的测试集直接验证，效果和我上面说的是一样的，是都需要先训练吗？

**Comment by whxueChris** [comment]
> > 
> 
> 你好，必须要用自己的数据集先训练，在用生成的模型进行测试是吗？ 另外，我使用你们的测试集直接验证，效果和我上面说的是一样的，是都需要先训练吗？

你好，请问一下子代码复现的过程中有遇到内存不足的情况吗，复现过程大概需要多少内存呢
