### ISSUE TITLE
测试有问题

### ISSUE THREAD

**Issue by songyn95** [BIT-DA/I2V-GAN#8]
你好，我使用下载的预训练模型，直接使用IRVI/single/traffic/testA 和IRVI/single/traffic/testB 两个文件夹下的数据进行测试，生成的结果中*_real_A.png明显和testA中是一样的，testB也是一样的。

下载的预训练模型放在I2V-GAN/checkpoints/experiment_name下，testA testB 放在I2V-GAN/img下 测试的命令如下：
python .\test.py --dataroot .\img\ --name experiment_name

我的问题是：
1. 生成的结果中*_real_A.png是预测的结果，而*_real_B.png是参照图像，描述是否正确？
2. 生成的结果为什么*_real_A.png和testA中是一样的，都是红外图，没有任何变化？

目前在研究这方面的算法，希望能得到你详细的解答，非常感谢！！！

**Comment by BingfengHan** [comment]
*_real是真实数据，不是生成结果
